version: 2.1



defaults: &defaults   ## anchor & aliases
    docker:
      - image: circleci/node:13.8.0

jobs:
   deploy-infrastructure:
    docker:
      - image: amazon/aws-cli     # Docker image here that supports AWS CLI
#    branches:                     # shows where this job can only be run on (certain branches)
#      only:
#        - master
#        - /rc-.*/     # any branch that starts with rc.... 
    steps:
      - checkout      # Checkout code from git
      - run: yum -y install tar gzip   # run as shell script
      - run: 
          name: Ensure back-end infrastructure is in place already
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
              --tags project=udapeople
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
              --tags project=udapeople
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            aws ec2 describe-instance \
              --filters "Name=tag:Name.Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text >> .circleci/ansible/inventory.txt
      - persist_to_workspace:       # Here's where you will add some code to rollback on failure  
          root: ~/
          paths:
            - project/.circleci/ansible/inventory.txt

workflows:
  default:
    jobs:
      - deploy-infrastructure:
       #   requires: [test-frontend, test-backend, scan-frontend, scan-backend]
       #   filters:
       #     branches:
       #       only: [test-feature-branch]

