version: 2.1
## Destroy environment only blueprint
commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      workflow_id: 
        type: string
      event:
        type: string
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            echo " Destroying Environment: "-<<parameters.workflow_id>>
            echo " aws s3 rm s3://udapeople-<<parameters.workflow_id>> --recursive "
            aws s3 rm s3://udapeople-<<parameters.workflow_id>> --recursive
            aws cloudformation delete-stack --stack-name udapeople-backend-<<parameters.workflow_id>>
            echo " aws cloudformation delete-stack --stack-name udapeople-backend-<<parameters.workflow_id>> "
            aws cloudformation delete-stack --stack-name udapeople-frontend-<<parameters.workflow_id>>

  revert-migrations:
    description: Revert the last migration if successfully run in the current workflow.
    parameters:
      workflow_id:
        type: string     
    steps:
      - run:
          name: Revert migrations 
          when: on_fail            # Add when this will run
          command: |
            # Curl command here to see if there was a successful migration associated with the workflow id, store result 
            npm run migrations:revert            
jobs:
  Revert-migrations:
    docker:
      - image: amazon/aws-cli     # Docker image here that supports AWS CLI
    steps:
      - checkout  
      - run: npm install      
      - run: exit 1  # kicks off the destroy-environment
      - revert-migrations:
          workflow_id: "5cfa402"  ###@@@@@"${CIRCLE_WORKFLOW_ID:0:7}"

workflows:
  Revert-1:
    jobs:
      - Revert-migrations

